import logging
print("python")
logging.basicConfig(level=logging.DEBUG)
logging.info('This is an info message')
logging.warning("This is a message")
logging.debug('This is a debug message')
logging.info('This is an info message')
logging.warning('This is a warning message')
logging.error('This is an error message')
logging.critical('This is a critical message')
